---
title: "Day 3 Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(ggplot2)
library(reshape2)
library(knitr)
library(dplyr)
library(stringr)
library(tidyverse)
library(readr)
library(collections)
options(scipen = 999)
```

```{r}
#input<-read_lines("Day3Sample.txt")
input<-read_lines("../../AoCData/AOC2019/Day3.txt")


```

## Part 1
I think I have to merely to store EVERY SINGLE POINT to see if there's going to be an intersection

```{r}
closestcross<-function(wire1,wire2){
  beenthere<-dict()
  wire1<-unlist(str_split(wire1,","))
  wire2<-unlist(str_split(wire2,","))
  ### map wire 1
  w1<-c(0,0)
  beenthere$set(str_flatten(w1," "),sum(w1)) 
  for(i in 1:length(wire1)){
    direction<-str_sub(wire1[i],1,1)
    distance<-as.numeric(str_sub(wire1[i],start=2))
    d<-1
    while(d<=distance){
      switch(direction,
             U=w1<-w1+c(0,1),
             D=w1<-w1+c(0,-1),
             L=w1<-w1+c(-1,0),
             R=w1<-w1+c(1,0),
             cat("bad w1 direction\n"))
      beenthere$set(str_flatten(w1," "),sum(w1)) 
      d<-d+1}}
  ### set up an intersection map
  intersections<-as.data.frame(matrix(ncol=0,nrow=0))
  ### crawl through w2
  w2<-c(0,0)
  beenthere$set(paste(w2),sum(w2)) 
  for(i in 1:length(wire2)){
    direction<-str_sub(wire2[i],1,1)
    distance<-as.numeric(str_sub(wire2[i],start=2))
    d<-1
    while(d<=distance){
      switch(direction,
             U=w2<-w2+c(0,1),
             D=w2<-w2+c(0,-1),
             L=w2<-w2+c(-1,0),
             R=w2<-w2+c(1,0),
             cat("bad w1 direction\n"))
      if(beenthere$has(str_flatten(w2," "))){intersections<-rbind(intersections,w2)}
      d<-d+1}}
  ###
  colnames(intersections)<-c("x","y")
  intersections<-intersections%>%rowwise%>%mutate(md=abs(x)+abs(y))
  min(intersections$md)}
```

```{r}
part1<-closestcross(input[1],input[2])
part1
```
## Part 2
```{r}
fastestcross<-function(wire1,wire2){
  beenthere<-dict()
  wire1<-unlist(str_split(wire1,","))
  wire2<-unlist(str_split(wire2,","))
  ### map wire 1
  w1<-c(0,0)
  t1<-1
  beenthere$set(str_flatten(w1," "),sum(w1)) 
  for(i in 1:length(wire1)){
    direction<-str_sub(wire1[i],1,1)
    distance<-as.numeric(str_sub(wire1[i],start=2))
    d<-1
    while(d<=distance){
      switch(direction,
             U=w1<-w1+c(0,1),
             D=w1<-w1+c(0,-1),
             L=w1<-w1+c(-1,0),
             R=w1<-w1+c(1,0),
             cat("bad w1 direction\n"))
      beenthere$set(str_flatten(w1," "),t1)
      t1<-t1+1
      d<-d+1}}
  ### set up an intersection map
  intersections<-as.data.frame(matrix(ncol=4,nrow=0))
  ### crawl through w2
  w2<-c(0,0)
  t2<-1
  beenthere$set(paste(w2),sum(w2)) 
  for(i in 1:length(wire2)){
    direction<-str_sub(wire2[i],1,1)
    distance<-as.numeric(str_sub(wire2[i],start=2))
    d<-1
    while(d<=distance){
      switch(direction,
             U=w2<-w2+c(0,1),
             D=w2<-w2+c(0,-1),
             L=w2<-w2+c(-1,0),
             R=w2<-w2+c(1,0),
             cat("bad w1 direction\n"))
      if(beenthere$has(str_flatten(w2," "))){
        intersections<-rbind(intersections,
                             c(w2,beenthere$get(str_flatten(w2," ")),t2))}
      t2<-t2+1
      d<-d+1}}
  ###
  colnames(intersections)<-c("x","y","t1","t2")
  intersections<-intersections%>%rowwise%>%mutate(besttime=t1+t2)
  min(intersections$besttime)}
```

```{r}
part2<-fastestcross(input[1],input[2])
part2
```




```{r,echo=FALSE}
basicgraph<-ggplot()+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position="none")+
  scale_y_reverse()+
  coord_fixed()
basicgraph
```

