---
title: "Day 24 Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(ggplot2)
library(reshape2)
library(knitr)
library(dplyr)
library(stringr)
library(tidyverse)
library(readr)
library(collections)
options(scipen = 999)
```

```{r}
input<-read_lines("Day24Sample.txt")
```

## Part 1

This is small enough so, I'm going to leave it as a matrix for now and regret that later.

```{r}
### Matrix
bugs<-matrix(nrow=length(input),ncol=nchar(input[1]))
for(i in 1:length(input)){bugs[i,]<-unlist(str_split(input[i],""))}

```

Standard - add a border around the outside, then update each level of the matrix

```{r}
bugger<-function(bm){
  beenthere<-dict()
  borderbm<-matrix(0,nrow=nrow(bm)+2,ncol=ncol(bm)+2)
  for(i in 1:nrow(bm)){
    for(j in 1:ncol(bm)){
      if(bm[j,i]=="#"){
      borderbm[(j+1),(i+1)]<-1}}}
  keepgoing<-TRUE
  roundcount<-1
  while(keepgoing){
    if(beenthere$has(str_flatten(borderbm))){
      keepgoing<-FALSE
      break}
    beenthere$set(str_flatten(borderbm),0)
    nextbm<-matrix(0,nrow=nrow(borderbm),ncol=ncol(borderbm))
    for(i in 2:(nrow(borderbm)-1)){
      for(j in 2:(ncol(borderbm)-1)){
        b<-borderbm[i,j]
        x<-borderbm[(i+1),j]+borderbm[(i-1),j]+borderbm[i,(j+1)]+borderbm[i,(j-1)]
        if(b==1){
          if(x!=1){nextbm[i,j]<-0}else{nextbm[i,j]<-1}
        }else if(b==0){
          if(x==1||x==2){nextbm[i,j]<-1}else{nextbm[i,j]<-0}}
        }}
    roundcount<-roundcount+1
    borderbm<-nextbm}
  biorating<-0
  for(i in (nrow(borderbm)-1):2){
      for(j in (ncol(borderbm)-1):2){
    biorating<-biorating*2+borderbm[i,j]}}
  biorating}
```

```{r}
bugger(bugs)
```

## Part 2
It's just going to be easier to do 24 separate formulas - which is insane.  But also kind of doable.

```{r}
bugline<-c(t(bugs))
```

```{r}
plutonian<-function(b,mins){
  ### transpose the matrix and turn it into a vector
  b<-c(t(b))[-13]
  b[which(b=="#")]<-1
  b[which(b==".")]<-0
  b<-as.numeric(b)
  ### to make sure there's enough space, just stick blank rows on each side in the list
  fullbl<-list()
  for(i in 1:(mins+1)){fullbl<-c(fullbl,list(c(rep(0,24))))}
  fullbl<-c(fullbl,list(b))
  for(i in 1:(mins+1)){fullbl<-c(fullbl,list(c(rep(0,24))))}
  ### run through each level
  m<-1
  while(m<=mins){
    nextbl<-list(c(rep(0,24)))
    for(i in 2:(length(fullbl)-1)){
      ### if the surrounding rows (and the current row) are all 0s, it's a 0.
      if((sum(fullbl[[i-1]])+sum(fullbl[[i]])+sum(fullbl[[i+1]]))==0){
        nextbl<-c(nextbl,list(c(rep(0,24))))
      ###   
      }else{
        lev<-c()
        for(j in 1:24){
          v<-fullbl[[i]][j]
          switch(as.character(j),
                 "1"=x<-fullbl[[i-1]][8]+fullbl[[i-1]][12]+fullbl[[i]][2]+fullbl[[i]][6],
                 "2"=x<-fullbl[[i-1]][8]+fullbl[[i]][1]+fullbl[[i]][3]+fullbl[[i]][7],
                 "3"=x<-fullbl[[i-1]][8]+fullbl[[i]][2]+fullbl[[i]][4]+fullbl[[i]][8],
                 "4"=x<-fullbl[[i-1]][8]+fullbl[[i]][3]+fullbl[[i]][5]+fullbl[[i]][9],
                 "5"=x<-fullbl[[i-1]][8]+fullbl[[i]][4]+fullbl[[i-1]][13]+fullbl[[i]][10],
                 "6"=x<-fullbl[[i]][1]+fullbl[[i-1]][12]+fullbl[[i]][7]+fullbl[[i]][11],
                 "7"=x<-fullbl[[i]][2]+fullbl[[i]][6]+fullbl[[i]][8]+fullbl[[i]][12],
                 "8"=x<-fullbl[[i]][3]+fullbl[[i]][7]+fullbl[[i]][9]+fullbl[[i+1]][1]+fullbl[[i+1]][2]+fullbl[[i+1]][3]+fullbl[[i+1]][4]+fullbl[[i+1]][5],
                 "9"=x<-fullbl[[i]][4]+fullbl[[i]][8]+fullbl[[i]][10]+fullbl[[i]][13],
                 "10"=x<-fullbl[[i]][5]+fullbl[[i]][9]+fullbl[[i-1]][13]+fullbl[[i]][14],
                 "11"=x<-fullbl[[i]][6]+fullbl[[i-1]][12]+fullbl[[i]][12]+fullbl[[i]][15],
                 "12"=x<-fullbl[[i]][7]+fullbl[[i]][11]+fullbl[[i+1]][1]+fullbl[[i+1]][6]+fullbl[[i+1]][11]+fullbl[[i+1]][15]+fullbl[[i+1]][20]+fullbl[[i]][16],
                 "13"=x<-fullbl[[i]][9]+fullbl[[i+1]][5]+fullbl[[i+1]][10]+fullbl[[i+1]][14]+fullbl[[i+1]][19]+fullbl[[i+1]][24]+fullbl[[i]][14]+fullbl[[i]][18],
                 "14"=x<-fullbl[[i]][10]+fullbl[[i]][13]+fullbl[[i-1]][13]+fullbl[[i]][19],
                 "15"=x<-fullbl[[i]][11]+fullbl[[i-1]][12]+fullbl[[i]][16]+fullbl[[i]][20],
                 "16"=x<-fullbl[[i]][12]+fullbl[[i]][15]+fullbl[[i]][17]+fullbl[[i]][21],
                 "17"=x<-fullbl[[i+1]][20]+fullbl[[i+1]][21]+fullbl[[i+1]][22]+fullbl[[i+1]][23]+fullbl[[i+1]][24]+fullbl[[i]][16]+fullbl[[i]][18]+fullbl[[i]][22],
                 "18"=x<-fullbl[[i]][13]+fullbl[[i]][17]+fullbl[[i]][19]+fullbl[[i]][23],
                 "19"=x<-fullbl[[i]][14]+fullbl[[i]][18]+fullbl[[i-1]][13]+fullbl[[i]][24],
                 "20"=x<-fullbl[[i]][15]+fullbl[[i-1]][12]+fullbl[[i]][21]+fullbl[[i-1]][17],
                 "21"=x<-fullbl[[i]][16]+fullbl[[i]][20]+fullbl[[i]][22]+fullbl[[i-1]][17],
                 "22"=x<-fullbl[[i]][17]+fullbl[[i]][21]+fullbl[[i]][23]+fullbl[[i-1]][17],
                 "23"=x<-fullbl[[i]][18]+fullbl[[i]][22]+fullbl[[i]][24]+fullbl[[i-1]][17],
                 "24"=x<-fullbl[[i]][19]+fullbl[[i]][23]+fullbl[[i-1]][13]+fullbl[[i-1]][17],
                 cat("something went wrong\n"))
          if(v==1){
            if(x!=1){lev<-c(lev,0)}else{lev<-c(lev,1)}
          }else if(v==0){
            if(x==1||x==2){lev<-c(lev,1)}else{lev<-c(lev,0)}
          }else{cat("I have no idea what went wrong\n")}}
        nextbl<-c(nextbl,list(lev))}}
    nextbl<-c(nextbl,list(c(rep(0,24))))
    fullbl<-nextbl
    m<-m+1}
  nextbl}
```

```{r}
p2<-plutonian(bugs,10)

part2<-sapply(1:length(p2),function(x){sum(p2[[x]])})
part2<-sum(part2)
part2

```

