---
title: "Day 9 Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(igraph)
library(ggplot2)
library(rgl)
library(ggraph)
library(reshape2)
library(knitr)
library(dplyr)
library(stringr)
library(tidyverse)
library(readr)
library(collections)
options(scipen = 999)
```

```{r}
input<-read_lines("../../AoCData/AOC2019/Day9.txt")
intcode<-as.numeric(unlist(str_split(input,",")))
```

Start with the computer - 
adding the relative base & the relative mode - also, extend the program

```{r}
iccomp<-function(prg,inp,starthere){
  i<-starthere
  outp<-0
  relativebase<-0
  while(prg[i]!=99){
    ## make sure that at least the next three numbers exist
    if((i+3)>length(prg)){
      prg<-c(prg,
             rep(0,(i+3-length(prg))))}
    opcode<-as.character(prg[i]%%100)
    firstp<-(prg[i]%/%100)%%10
    secondp<-(prg[i]%/%1000)%%10
    thirdp<-prg[i]%/%10000
    #  cat("i: ",i," fullinst: ",prg[i]," opcode: ",opcode,"\n")
    switch(opcode,
           ### add
           "1"={
             a<-prg[i+1]
             if(firstp==0){a<-prg[a+1]}
             if(firstp==2){a<-prg[a+1+relativebase]}
             b<-prg[i+2]
             if(secondp==0){b<-prg[b+1]}
             if(secondp==2){b<-prg[b+1+relativebase]}
             if(is.na(a)){a<-0}
             if(is.na(b)){b<-0}
             c<-prg[i+3]
             if(thirdp==2){c<-prg[i+3]+relativebase}
             prg[c+1]<-a+b
             i<-i+4},
           ### multiply
           "2"={
             a<-prg[i+1]
             if(firstp==0){a<-prg[a+1]}
             if(firstp==2){a<-prg[a+1+relativebase]}
             b<-prg[i+2]
             if(secondp==0){b<-prg[b+1]}
             if(secondp==2){b<-prg[b+1+relativebase]}
             if(is.na(a)){a<-0}
             if(is.na(b)){b<-0}
             c<-prg[i+3]
             if(thirdp==2){c<-prg[i+3]+relativebase}
             prg[c+1]<-a*b
             i<-i+4},
           ### input
           "3"={
             if(firstp==0){a<-prg[i+1]}
             if(firstp==2){a<-prg[i+1]+relativebase}
             if(is.na(a)){a<-0}
             if(length(inp)==0){
               cat("waiting---\n")
               return(list(prg,outp,i))
             }else{
               cat("input: ",inp[1]," - ")
               prg[a+1]<-inp[1]
               inp<-inp[-1]
               i<-i+2}},
           ### output
           "4"={
             a<-prg[i+1]
             if(firstp==0){a<-prg[a+1]}
             if(firstp==2){a<-prg[a+1+relativebase]}
             if(is.na(a)){a<-0}
             cat("output: ",a,"\n")
             outp<-a
             i<-i+2},
           ### jump if true
           "5"={
             a<-prg[i+1]
             if(firstp==0){a<-prg[a+1]}
             if(firstp==2){a<-prg[a+1+relativebase]}
             b<-prg[i+2]
             if(secondp==0){b<-prg[b+1]}
             if(secondp==2){b<-prg[b+1+relativebase]}
             if(is.na(a)){a<-0}
             if(is.na(b)){b<-0}
             if(a!=0){i<-b+1}else{i<-i+3}},
           ### jump if false
           "6"={
             a<-prg[i+1]
             if(firstp==0){a<-prg[a+1]}
             if(firstp==2){a<-prg[a+1+relativebase]}
             b<-prg[i+2]
             if(secondp==0){b<-prg[b+1]}
             if(secondp==2){b<-prg[b+1+relativebase]}
             if(is.na(a)){a<-0}
             if(is.na(b)){b<-0}
             if(a==0){i<-b+1}else{i<-i+3}},
           ### less than
           "7"={
             a<-prg[i+1]
             if(firstp==0){a<-prg[a+1]}
             if(firstp==2){a<-prg[a+1+relativebase]}
             b<-prg[i+2]
             if(secondp==0){b<-prg[b+1]}
             if(secondp==2){b<-prg[b+1+relativebase]}
             if(is.na(a)){a<-0}
             if(is.na(b)){b<-0}
             c<-prg[i+3]
             if(thirdp==2){c<-prg[i+3]+relativebase}
             if(a<b){prg[c+1]<-1}else{prg[c+1]<-0}
             i<-i+4},
           "8"={
             a<-prg[i+1]
             if(firstp==0){a<-prg[a+1]}
             if(firstp==2){a<-prg[a+1+relativebase]}
             b<-prg[i+2]
             if(secondp==0){b<-prg[b+1]}
             if(secondp==2){b<-prg[b+1+relativebase]}
             if(is.na(a)){a<-0}
             if(is.na(b)){b<-0}
             c<-prg[i+3]
             if(thirdp==2){c<-prg[i+3]+relativebase}
             if(a==b){prg[c+1]<-1}else{prg[c+1]<-0}
             i<-i+4},
           "9"={
             a<-prg[i+1]
             if(firstp==0){a<-prg[a+1]}
             if(firstp==2){a<-prg[a+1+relativebase]}
             if(is.na(a)){a<-0}
             relativebase<-relativebase+a
             i<-i+2},
           {cat(i,": unknown opcode",opcode,"\n")
             break})
    prg<-replace(prg,is.na(prg),0)}
  #  cat("ENDING i: ",i," fullinst: ",prg[i]," opcode: ",opcode,"\n")
  
  return(list(prg,outp,0))}
```


Tests to see if this works
```{r}
iccomp(prg=c(109,1,204,-1,1001,100,1,100,1008,100,16,101,1006,101,0,99),12341,1)[[2]] # input
iccomp(prg=c(1102,34915192,34915192,7,4,7,99,0),12341,1)[[2]] # -1
iccomp(prg=c(104,1125899906842624,99),12341,1)[[2]] # -1

```

More tests to see if this works
```{r}
iccomp(prg=c(109, -1, 4, 1, 99),12341,1)[[2]] # -1
iccomp(prg=c(109, -1, 104, 1, 99),12341,1)[[2]] # 1
iccomp(prg=c(109, -1, 204, 1, 99),12341,1)[[2]] # 109
iccomp(prg=c(109, 1, 9, 2, 204, -6, 99),12341,1)[[2]] # 204
iccomp(prg=c(109, 1, 109, 9, 204, -6, 99),12341,1)[[2]] # 204
iccomp(prg=c(109, 1, 209, -1, 204, -106, 99),12341,1)[[2]] # 204
iccomp(prg=c(109, 1, 3, 3, 204, 2, 99),12341,1)[[2]] # input
iccomp(prg=c(109, 1, 203, 2, 204, 2, 99),12341,1)[[2]] # input
```



```{r}
p1<-iccomp(intcode,1,1)
part1<-p1[[2]]
part1
```
## Part 2

```{r}
p2<-iccomp(prg=intcode,inp=2,starthere=1)
part2<-p2[[2]]
part2
```

